backend/controllers/OrderController.php
<?php

namespace backend\controllers;

use src\repositories\shop\OrderRepository;
use Yii;
use src\entities\shop\Order;
use src\forms\shop\OrderEditForm;
use src\services\shop\OrderService;
use backend\search\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use src\repositories\shop\OrderitemRepository;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    private $orderitems;
    private $service;
    private $orders;

    public function __construct(
        $id, 
        $module, 
        OrderitemRepository $orderitems, 
        OrderService $service,
        OrderRepository $orders,
        array $config = []
    )
    {
        $this->orderitems = $orderitems;
        $this->service = $service;
        $this->orders = $orders;
        parent::__construct($id, $module, $config);
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'orderstructs'=>$this->orderitems->findWithProducts($id)
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $order = $this->findModel($id);
        
        $form = new OrderEditForm($order);
        if ($form->load(Yii::$app->request->post()) && $form->validate()) 
        {
           try
           {
                $this->service->edit($form, $order->id);
                return $this->redirect(['index']);
           }
            catch(\DomainException $e)
            {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('update', [
            'model' => $form,
            'order' => $order
        ]);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try {
            $this->service->remove($id);
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
        }
        return $this->redirect(['index']);
    }
    
    public function actionGetstruct($id)
    {
        return $this->renderAjax('_struct', [
            'orderstructs'=>$this->orderitems->findWithProducts($id)
        ]);
    }

    public function actionInvoice($ids)
    {
        Yii::$app->response->format = 'pdf';
        $orders  = $this->orders->getOrders(explode(',', $ids));
        return $this->render('invoice', [
            'orders' => $orders,
        ]);
    }


    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\helpers\Json;
use src\services\cart\CartService;
use src\repositories\shop\ProductRepository;
use yii\filters\VerbFilter;


class CartController extends \yii\web\Controller
{
    private $service;
    private $products;
    
    public function __construct(
        $id, 
        $module, 
        CartService $service, 
        ProductRepository $products,
        $config = []
    )
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
        $this->products = $products;
    }
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'del-from-cart' => ['POST']
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $cartdata = $this->service->getCart();
        
        $ids = $cartdata['ids'];
        $total = $cartdata['price'];
        $products = $this->service->getProducts();
        
        return $this->render('index',[
            'products'=>$products,
            'ids'=>$ids,
            'total'=>$total,
        ]);
    }

    public function actionAddToCart($id, $size, $amount=1)
    {
        try{
            $product = $this->products->get($id);
            $data = $this->service->addToCart($product, $size, $amount);
            return Json::encode($data);
        } catch (\DomainException $e)
        {
            return $e->getMessage();
        }
    }
    public function actionDelFromCart($id, $size)
    {
        try{
            $product = $this->products->get($id);
            $this->service->delFromCart($product, $size);
            return $this->redirect(Yii::$app->request->referrer);
        } catch (\DomainException $e)
        {
            return $e->getMessage();
        }
    }
    public function actionUnsetCart()
    {
        $this->service->unsetCart();
    }
}

frontend/controllers/ProductController.php
<?php
namespace frontend\controllers;

use src\entities\shop\Product;
use src\entities\shop\Sizetable;
use src\forms\shop\CalcSizeForm;
use src\repositories\SettingsRepository;
use Yii;
use yii\web\Controller;
use src\repositories\shop\SectionRepository;
use src\repositories\shop\CategoryRepository;
use src\repositories\shop\ProductRepository;

class ProductController extends Controller
{
    private $sections;
    private $categories;
    private $products;
    private $settings;

    public function __construct(
        $id, 
        $module, 
        CategoryRepository $categories, 
        SectionRepository $sections, 
        ProductRepository $products,
        SettingsRepository $settings,
        array $config = []
    )
    {
        $this->sections = $sections;
        $this->categories = $categories;
        $this->products = $products;
        $this->settings = $settings;
        parent::__construct($id, $module, $config);
    }
    
    public function actionCatalog($section, $category = null, $sizes = null, $sort = null)
    {
        $section = $this->sections->getByAlias($section);
        $category = $category ? $this->categories->getByAlias($section->id, $category) : null;
        $provider = $this->products->findForCatalog($section->id, $category->id, $sizes, $sort);
        return $this->render('catalog', [
            'section' => $section,
            'category' => $category,
            'sizes' => $sizes,
            'provider' => $provider,
            'sort' =>$sort
        ]);
    }
    public function actionSale($section = false)
    {
        $section = $section ? $this->sections->getByAlias($section) : null;
        $provider = $this->products->findSale($section->id);
        return $this->render('sale', [
            'provider' => $provider,
            'sections' => $this->sections->findAllSections(),
            'section' => $section,
            'settings' => $this->settings->getSale(),
        ]);
    }
    public function actionArchive($section = null, $category = null, $sizes = null, $sort = null)
    {
        $section = $section ? $this->sections->getByAlias($section) : null;
        $category = $category ? $this->categories->getByAlias($section->id, $category) : null;
        $provider = $this->products->findForArchive($section->id, $category->id, $sizes, $sort);
        return $this->render('archive', [
            'section' => $section,
            'category' => $category,
            'sizes' => $sizes,
            'provider' => $provider,
            'sort' =>$sort,
            'settings' => $this->settings->getArchive(),
        ]);
    }
    public function actionProduct($alias)
    {
        $product = $this->products->getByAlias($alias);
        $form = new CalcSizeForm();

        $sizesW = Sizetable::getSizesW();
        $sizesM = Sizetable::getSizesM();
        if ($form->load(Yii::$app->request->post()) && $form->validate())
        {
            try
            {
                if($form->chest)
                    $sizeChest = Sizetable::getSizeChest($form->gender, $form->chest);
                if($form->thigh)
                    $sizeThigh = Sizetable::getSizeThigh($form->gender, $form->thigh);
            }
            catch(\DomainException $e)
            {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('product',[
            'product'=>$product,
            'model' => $form,
            'sizeChest' => $sizeChest,
            'sizeThigh' => $sizeThigh,
            'sizesM' => $sizesM,
            'sizesW' => $sizesW,
        ]);
    }
}

frontend/views/cart/index.php
<?php 
use yii\helpers\Url;
use yii\helpers\Html;
$this->title = "Корзина покупок";
?>
<div class="check-out">
    <div class="container">
        <div class="row">
            <h1>Корзина покупок</h1>
        </div>
        <?php if($ids){?>
    	<div class="bs-example4" data-example-id="simple-responsive-table">
            <div class="table-responsive">
                <table class="table-heading">
                    <tr>
                        <th>Фото</th>	
                        <th>Товар</th>	
                        <th>Размер</th>	
                        <th>Цена</th>
                        <th>Количество </th>
                        <th>Стоимость</th>
                        <th>Удалить</th>
                    </tr>
                    <?php $i=0; foreach($products as $prod){?>
                    <tr class="cart-header">
                        <td>
                            <a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>" class="at-in">
                                <img src="/frontend/web/img/<?=$prod->photo;?>" class="img-responsive" alt="<?=$prod->name;?>"/>
                            </a>
                        </td>
                    	<td>
                        	<div class="sed">
                        		<h5><a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><?=$prod->name;?></a></h5>
                        	</div>
                        </td>
                        <td>
                            <span class="label label-info"><?=$ids[$i]['size'];?></span>
                        </td>
                        <td><?=$ids[$i]['price'];?> грн.</td>
                    	<td><?=$ids[$i]['count'];?></td>
                    	<td class="item_price"><?=$prod->real_price * $ids[$i]['count'];?> грн.</td>
                    	<td>
                            <?= Html::a('<div class="close1"> </div>', ['cart/del-from-cart', 'id' => $prod->id, 'size' => $ids[$i]['size']], [ 'data' => ['confirm' => 'Вы уверены, что желаете удалить товар?','method' => 'post']]) ?>
                        </td>
                        
                    </tr>
                    <?php $i++; }?>
                </table>
        	</div>
    	</div>
        <div class="panel panel-default">
          <div class="panel-heading">Общая стоимость:</div>
          <div class="panel-body">
                <?=$total;?> грн.
          </div>
        </div>
    	<div class="produced">
    	   <a href="<?=Url::toRoute(['order/index']);?>" class="hvr-skew-backward">Сделать заказ</a>
    	</div>
        <?php } else {?>
        <div class="alert alert-danger" role="alert">Вы еще не добавляли товар в корзину</div>
        <?php }?>
    </div>
</div>