backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use src\forms\LoginForm;
use src\services\auth\AuthService;

/**
 * Site controller
 */
class SiteController extends Controller
{
    private $authService;

    public function __construct($id, $module, AuthService $authService, array $config = [])
    {
        $this->authService = $authService;
        parent::__construct($id, $module, $config);
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout='main-login';
        $form = new LoginForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate())
        {
            try {
                $user = $this->authService->auth($form);
                Yii::$app->user->login($user, $form->rememberMe ? 3600 * 24 * 30 : 0);
                return $this->goBack();
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('login', [
            'model' => $form,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/InfoController.php
<?php
namespace frontend\controllers;

use src\repositories\info\InfoRepository;
use yii\web\Controller;


/**
 * Info controller
 */
class InfoController extends Controller
{
    private $infos;

    public function __construct(
        $id,
        $module,
        InfoRepository $infos,
        array $config = [])
    {
        $this->infos = $infos;
        parent::__construct($id, $module, $config);
    }
    /**
     * @inheritdoc
     */

    /**
     * Displays info page.
     *
     * @return mixed
     */
    public function actionInfo($alias)
    {
        $info = $this->infos->getPage($alias);

        return $this->render('info', [
            'info' => $info,
        ]);
    }

}

frontend/controllers/ProductController.php
<?php
namespace frontend\controllers;

use src\entities\shop\Product;
use src\entities\shop\Sizetable;
use src\forms\shop\CalcSizeForm;
use src\repositories\SettingsRepository;
use Yii;
use yii\web\Controller;
use src\repositories\shop\SectionRepository;
use src\repositories\shop\CategoryRepository;
use src\repositories\shop\ProductRepository;

class ProductController extends Controller
{
    private $sections;
    private $categories;
    private $products;
    private $settings;

    public function __construct(
        $id, 
        $module, 
        CategoryRepository $categories, 
        SectionRepository $sections, 
        ProductRepository $products,
        SettingsRepository $settings,
        array $config = []
    )
    {
        $this->sections = $sections;
        $this->categories = $categories;
        $this->products = $products;
        $this->settings = $settings;
        parent::__construct($id, $module, $config);
    }
    
    public function actionCatalog($section, $category = null, $sizes = null, $sort = null)
    {
        $section = $this->sections->getByAlias($section);
        $category = $category ? $this->categories->getByAlias($section->id, $category) : null;
        $provider = $this->products->findForCatalog($section->id, $category->id, $sizes, $sort);
        return $this->render('catalog', [
            'section' => $section,
            'category' => $category,
            'sizes' => $sizes,
            'provider' => $provider,
            'sort' =>$sort
        ]);
    }
    public function actionSale($section = false)
    {
        $section = $section ? $this->sections->getByAlias($section) : null;
        $provider = $this->products->findSale($section->id);
        return $this->render('sale', [
            'provider' => $provider,
            'sections' => $this->sections->findAllSections(),
            'section' => $section,
            'settings' => $this->settings->getSale(),
        ]);
    }
    public function actionArchive($section = null, $category = null, $sizes = null, $sort = null)
    {
        $section = $section ? $this->sections->getByAlias($section) : null;
        $category = $category ? $this->categories->getByAlias($section->id, $category) : null;
        $provider = $this->products->findForArchive($section->id, $category->id, $sizes, $sort);
        return $this->render('archive', [
            'section' => $section,
            'category' => $category,
            'sizes' => $sizes,
            'provider' => $provider,
            'sort' =>$sort,
            'settings' => $this->settings->getArchive(),
        ]);
    }
    public function actionProduct($alias)
    {
        $product = $this->products->getByAlias($alias);
        $form = new CalcSizeForm();

        $sizesW = Sizetable::getSizesW();
        $sizesM = Sizetable::getSizesM();
        if ($form->load(Yii::$app->request->post()) && $form->validate())
        {
            try
            {
                if($form->chest)
                    $sizeChest = Sizetable::getSizeChest($form->gender, $form->chest);
                if($form->thigh)
                    $sizeThigh = Sizetable::getSizeThigh($form->gender, $form->thigh);
            }
            catch(\DomainException $e)
            {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('product',[
            'product'=>$product,
            'model' => $form,
            'sizeChest' => $sizeChest,
            'sizeThigh' => $sizeThigh,
            'sizesM' => $sizesM,
            'sizesW' => $sizesW,
        ]);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use src\entities\Slider;
use src\repositories\SettingsRepository;
use Yii;
use yii\web\Controller;
use src\repositories\shop\SectionRepository;
use src\repositories\shop\ProductRepository;

/**
 * Site controller
 */
class SiteController extends Controller
{
    private $sections;
    private $categories;
    private $products;
    private $settings;

    public function __construct(
        $id,
        $module,
        SectionRepository $sections,
        ProductRepository $products,
        SettingsRepository $settings,
        array $config = [])
    {
        $this->sections = $sections;
        $this->products = $products;
        $this->settings = $settings;
        parent::__construct($id, $module, $config);
    }
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index',[
            'sections' => $this->sections->findAllSections(),
            'products' => $this->products->findProdsToMainPage(),
            'settings' => $this->settings->getMain(),
            'slider' => Slider::find()->orderBy('position')->all(),
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use yii\helpers\Url;

$this->title = $settings->main_seo_title;

$this->registerMetaTag([
    'name'=>'description',
    'content'=>$settings->main_seo_text
]);
$this->registerMetaTag([
    'name'=>'keywords',
    'content'=>$settings->main_seo_keys
]);
?>
<!--content-->
<div class="content main_page">
    <div class="container-fluid slider_main">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <?php for($i=0; $i<count($slider); $i++){?>
                    <li data-target="#carousel-example-generic" data-slide-to="<?=$i;?>" class="<?php if($i==0) echo "active"?>"></li>
                <?php }?>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <?php $j = 0; foreach($slider as $slide){ ?>
                    <div class="item <?php if($j==0) echo "active"?>">
                        <a href="<?= $slide->href ;?>">
                            <img src="/frontend/web/img/<?= $slide->photo ;?>" />
                        </a>
                    </div>
                    <?php $j=1;} ?>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="main_text">
	    <div class="container">
            <div class="col-md-12">
                <h1><?= $settings->main_h1;?></h1>
                <p><?= $settings->main_text;?></p>
            </div>
            <!-- </div>
    </div>

            <!--<div class="content-top">
            <div class="col-md-6 col-md">
				<div class="col-2">
					<img src="/frontend/web/img/<?= $settings->main_img;?>" class="img-responsive" />
				</div>
			</div>
			<div class="col-md-6 col-md">
				<div class="col-2">
					<h1><?= $settings->main_h1;?></h1>
                    <p><?= $settings->main_text;?></p>
					<a href="<?= Url::toRoute(['info/info', 'alias'=> 'o-nas']);?>" class="buy-now">Подробнее про нас</a>
				</div>
			</div>
            <div class="clearfix"></div>
            <!--
            <?php foreach($sections as $section){?>
			<div class="col-md-6 col-md1">
				<div class="col-3">
					<a href="<?=Url::toRoute(['product/catalog', 'section'=>$section->alias]);?>"><img src="/frontend/web/img/<?=$section->photo;?>" class="img-responsive" alt="<?=$section->name;?>"/>
					<div class="col-pic">
						<p>Одежда</p>
						<label></label>
						<h5><?=$section->name;?></h5>
					</div></a>
				</div>
            </div>
            <?php }?>
			<div class="clearfix"></div>
		</div>
		<!--products-->
            <!-- <div class="container"> -->
    <?php if($products['home']) { ?>
	<div class="content-mid">
		<h3>Домашняя одежда</h3>
		<label class="line"></label>
		<div class="mid-popular">
            <div class="rec_slider">
                <?php foreach($products['home'] as $prod){?>
                    <div class="one_item">
                        <div class="col-md-12 item-grid">
                            <div class="mid-pop">
                                <div class="pro-img">
                                    <img src="/frontend/web/img/<?=$prod->thumb;?>" class="img-responsive" alt="<?=$prod->name;?>">
                                    <div class="zoom-icon ">
                                        <a class="picture" href="/frontend/web/img/<?=$prod->photo;?>" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                                        <a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                                    </div>
                                </div>
                                <div class="mid-1">
                                    <div class="women">
                                        <span><?=$prod->category->name;?></span>
                                        <h6><a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><?=$prod->name;?></a></h6>
                                    </div>
                                    <div class="mid-2">
                                        <p ><?php if($prod->sale){?><label><?=$prod->price;?> грн.</label><?php }?><em class="item_price"><?=$prod->real_price;?> грн.</em></p>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>

                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                                <div class="divwithbut">
                                    <a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Подробнее</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php }?>
            </div>
		</div>
	</div>
    <?php } ?>
    <?php if($products['rest']) { ?>
    <div class="content-mid">
        <h3>Одежда для отдыха</h3>
        <label class="line"></label>
        <div class="mid-popular">
            <div class="rec_slider">
                <?php foreach($products['rest'] as $prod){?>
                    <div class="one_item">
                        <div class="col-md-12 item-grid">
                            <div class="mid-pop">
                                <div class="pro-img">
                                    <img src="/frontend/web/img/<?=$prod->thumb;?>" class="img-responsive" alt="<?=$prod->name;?>">
                                    <div class="zoom-icon ">
                                        <a class="picture" href="/frontend/web/img/<?=$prod->photo;?>" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                                        <a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                                    </div>
                                </div>
                                <div class="mid-1">
                                    <div class="women">
                                        <span><?=$prod->category->name;?></span>
                                        <h6><a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><?=$prod->name;?></a></h6>
                                    </div>
                                    <div class="mid-2">
                                        <p ><?php if($prod->sale){?><label><?=$prod->price;?> грн.</label><?php }?><em class="item_price"><?=$prod->real_price;?> грн.</em></p>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>

                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                                <div class="divwithbut">
                                    <a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Подробнее</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php }?>
            </div>
        </div>
    </div>
    <?php } ?>
    <?php if($products['casual']) { ?>
    <div class="content-mid">
        <h3>Повседневная одежда</h3>
        <label class="line"></label>
        <div class="mid-popular">
            <div class="rec_slider">
                <?php foreach($products['casual'] as $prod){?>
                    <div class="one_item">
                        <div class="col-md-12 item-grid">
                            <div class="mid-pop">
                                <div class="pro-img">
                                    <img src="/frontend/web/img/<?=$prod->thumb;?>" class="img-responsive" alt="<?=$prod->name;?>">
                                    <div class="zoom-icon ">
                                        <a class="picture" href="/frontend/web/img/<?=$prod->photo;?>" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                                        <a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                                    </div>
                                </div>
                                <div class="mid-1">
                                    <div class="women">
                                        <span><?=$prod->category->name;?></span>
                                        <h6><a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><?=$prod->name;?></a></h6>
                                    </div>
                                    <div class="mid-2">
                                        <p ><?php if($prod->sale){?><label><?=$prod->price;?> грн.</label><?php }?><em class="item_price"><?=$prod->real_price;?> грн.</em></p>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>

                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                                <div class="divwithbut">
                                    <a href="<?=Url::toRoute(['product/product', 'alias'=>$prod->alias]);?>"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Подробнее</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php }?>
            </div>
        </div>
    </div>
    <?php } ?>
	<!--//products-->
        </div> </div>
	
</div>
<!--//content-->